// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqzlwok1sTkFzgW24h9Jw0B90cnT2V_Y',
    appId: '1:105427420864:android:b986918e5fcb03f6d18f25',
    messagingSenderId: '105427420864',
    projectId: 'blocpractice-c968b',
    databaseURL: 'https://blocpractice-c968b-default-rtdb.firebaseio.com',
    storageBucket: 'blocpractice-c968b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATmxnaDnlsqq4KIihLc82loACKBke-Bys',
    appId: '1:105427420864:ios:b6b26b90b559a5f2d18f25',
    messagingSenderId: '105427420864',
    projectId: 'blocpractice-c968b',
    databaseURL: 'https://blocpractice-c968b-default-rtdb.firebaseio.com',
    storageBucket: 'blocpractice-c968b.firebasestorage.app',
    iosBundleId: 'com.example.dopamineDetoxApp',
  );
}
